"""Initial tables

Revision ID: c557cdfff56c
Revises: 
Create Date: 2025-10-23 18:49:38.799584

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c557cdfff56c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_key',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('request_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('response_body', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sqlite.DATETIME(), nullable=False),
    sa.Column('expires_at', sqlite.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sku', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sqlite.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('service_credentials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_name', sa.VARCHAR(), nullable=False),
    sa.Column('service_secret', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_credentials')
    op.drop_table('inventory')
    op.drop_table('idempotency_key')
    # ### end Alembic commands ###
